ALTER TABLE maps ADD COLUMN owner_id TEXT;
ALTER TABLE maps ADD COLUMN shared INTEGER DEFAULT 0;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT UNIQUE, name TEXT, pass_hash TEXT, salt TEXT, google_sub TEXT UNIQUE, plan TEXT DEFAULT 'lite', pro_requested INTEGER DEFAULT 0, created_at INTEGER);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS snapshots (map_id TEXT NOT NULL, idx INTEGER NOT NULL, state TEXT NOT NULL, PRIMARY KEY (map_id, idx));
CREATE TABLE IF NOT EXISTS exports (user_id TEXT NOT NULL, month TEXT NOT NULL, count INTEGER DEFAULT 0, PRIMARY KEY (user_id, month));
CREATE INDEX IF NOT EXISTS maps_owner ON maps (owner_id);
