// Impressum, Datenschutzerklärung and AGB in German (binding), English and Russian.
// Operator data comes from environment variables; anything missing is shown in red so it is noticed before launch.
// These texts are a careful starting point, not legal advice: have them checked by a lawyer before going live.
import { esc } from './mail.js';

export const TERMS_VERSION = '2026-10';
const UPDATED = { de: 'Stand: Oktober 2026', en: 'Last updated: October 2026', ru: 'Редакция: октябрь 2026' };
const LANGS = ['de', 'en', 'ru'];

export function pickLang(request) {
  const q = new URL(request.url).searchParams.get('lang');
  if (LANGS.includes(q)) return q;
  const al = (request.headers.get('accept-language') || '').toLowerCase();
  if (al.startsWith('de')) return 'de';
  if (al.startsWith('ru')) return 'ru';
  return 'en'; // other languages get the English translation; the German text stays the binding one
}

function operator(env, l) {
  const miss = (k) => `<mark class="miss">[${k} ${l === 'de' ? 'fehlt' : l === 'ru' ? 'не задан' : 'missing'}]</mark>`;
  const v = (k) => (env[k] ? esc(env[k]) : null);
  const need = (k) => v(k) || miss(k);
  const country = v('LEGAL_COUNTRY') || { de: 'Deutschland', en: 'Germany', ru: 'Германия' }[l];
  return {
    name: need('LEGAL_NAME'), street: need('LEGAL_STREET'), zipCity: need('LEGAL_ZIP_CITY'), country,
    email: env.LEGAL_EMAIL ? `<a href="mailto:${esc(env.LEGAL_EMAIL)}">${esc(env.LEGAL_EMAIL)}</a>` : miss('LEGAL_EMAIL'),
    phone: v('LEGAL_PHONE'), vat: v('LEGAL_VAT_ID'), register: v('LEGAL_REGISTER'), responsible: v('LEGAL_RESPONSIBLE'),
    small: env.LEGAL_SMALL_BUSINESS === '1' || env.LEGAL_SMALL_BUSINESS === 'true',
    address() { return `${this.name}<br>${this.street}<br>${this.zipCity}<br>${this.country}`; },
  };
}
// Which services are actually switched on decides which sections the privacy policy contains.
function services(env) {
  return { ai: env.ANTHROPIC_API_KEY ? 'anthropic' : env.AI ? 'workers' : env.MOCK === '1' ? 'none' : 'workers', google: !!env.GOOGLE_CLIENT_ID, mail: !!env.RESEND_API_KEY, prints: !!env.PRINTS };
}

// ---------------- Impressum ----------------
function impressum(env, l) {
  const o = operator(env, l);
  if (l === 'de') return `<h1>Impressum</h1>
<h2>Angaben gemäß § 5 DDG</h2><p>${o.address()}</p>
<h2>Kontakt</h2><p>E-Mail: ${o.email}${o.phone ? `<br>Telefon: ${o.phone}` : ''}</p>
${o.register ? `<h2>Registereintrag</h2><p>${o.register}</p>` : ''}
${o.vat ? `<h2>Umsatzsteuer-ID</h2><p>Umsatzsteuer-Identifikationsnummer gemäß § 27a UStG: ${o.vat}</p>` : ''}
${o.small ? '<p>Kleinunternehmer im Sinne von § 19 UStG; es wird keine Umsatzsteuer ausgewiesen.</p>' : ''}
<h2>Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV</h2><p>${o.responsible || o.name}, Anschrift wie oben.</p>
<h2>Verbraucherstreitbeilegung</h2><p>Wir sind nicht bereit und nicht verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p>
<h2>Kartendaten</h2><p>Grundkarte: Made with Natural Earth (gemeinfrei). Relief: ETOPO1, NOAA National Centers for Environmental Information, und Natural Earth (gemeinfrei). Ortssuche und Stadtausschnitte: © OpenStreetMap-Mitwirkende (ODbL), Nominatim; Stadtausschnitte: OpenFreeMap, © OpenMapTiles.</p>`;
  if (l === 'ru') return `<h1>Impressum (выходные данные)</h1><p class="tr">Перевод для удобства. Юридическую силу имеет немецкая версия.</p>
<h2>Сведения согласно § 5 DDG</h2><p>${o.address()}</p>
<h2>Контакты</h2><p>E-mail: ${o.email}${o.phone ? `<br>Телефон: ${o.phone}` : ''}</p>
${o.register ? `<h2>Регистрационная запись</h2><p>${o.register}</p>` : ''}
${o.vat ? `<h2>Номер плательщика НДС</h2><p>USt-IdNr. согласно § 27a UStG: ${o.vat}</p>` : ''}
${o.small ? '<p>Малый предприниматель согласно § 19 UStG; НДС не начисляется.</p>' : ''}
<h2>Ответственный за содержание (§ 18 абз. 2 MStV)</h2><p>${o.responsible || o.name}, адрес указан выше.</p>
<h2>Урегулирование споров с потребителями</h2><p>Мы не готовы и не обязаны участвовать в процедурах урегулирования споров в арбитражном органе по делам потребителей.</p>
<h2>Картографические данные</h2><p>Основа карты: Natural Earth (общественное достояние). Рельеф: ETOPO1, NOAA, и Natural Earth (общественное достояние). Поиск мест и врезки городов: © участники OpenStreetMap (ODbL), Nominatim; town insets: OpenFreeMap, © OpenMapTiles.</p>`;
  return `<h1>Legal notice (Impressum)</h1><p class="tr">Translation for convenience. The German version is legally binding.</p>
<h2>Information pursuant to § 5 DDG</h2><p>${o.address()}</p>
<h2>Contact</h2><p>E-mail: ${o.email}${o.phone ? `<br>Phone: ${o.phone}` : ''}</p>
${o.register ? `<h2>Register entry</h2><p>${o.register}</p>` : ''}
${o.vat ? `<h2>VAT ID</h2><p>VAT identification number pursuant to § 27a UStG: ${o.vat}</p>` : ''}
${o.small ? '<p>Small business under § 19 UStG; no VAT is charged.</p>' : ''}
<h2>Responsible for content under § 18 (2) MStV</h2><p>${o.responsible || o.name}, address as above.</p>
<h2>Consumer dispute resolution</h2><p>We are neither willing nor obliged to take part in dispute resolution proceedings before a consumer arbitration board.</p>
<h2>Map data</h2><p>Base map: made with Natural Earth (public domain). Relief: ETOPO1, NOAA National Centers for Environmental Information, and Natural Earth (public domain). Place search and town insets: © OpenStreetMap contributors (ODbL), Nominatim; врезки городов: OpenFreeMap, © OpenMapTiles.</p>`;
}

// ---------------- Datenschutz ----------------
function privacy(env, l) {
  const o = operator(env, l), s = services(env);
  const T = {
    de: {
      h: 'Datenschutzerklärung',
      ctrl: `<h2>1. Verantwortlicher</h2><p>${o.address()}<br>E-Mail: ${o.email}</p><p>Einen Datenschutzbeauftragten haben wir nicht benannt, weil keine gesetzliche Pflicht dazu besteht.</p>`,
      over: `<h2>2. Das Wichtigste in Kürze</h2><ul><li>Wir verwenden keine Analyse- oder Werbe-Tracker und keine Cookies von Dritten. Schriften und Kartenbibliotheken werden von unserem eigenen Server geladen.</li><li>Ihre Karten sind privat, bis Sie selbst einen Link freigeben.</li><li>Wir verkaufen keine Daten und verwenden Ihre Inhalte nicht zum Training von KI-Modellen.</li><li>Sie können Ihre Daten jederzeit im Kontomenü herunterladen und Ihr Konto mit allen Karten löschen.</li></ul>`,
      host: `<h2>3. Hosting und Server-Protokolle</h2><p>Die Website läuft auf Cloudflare Pages; Datenbank (D1) und Funktionen werden ebenfalls von der Cloudflare, Inc., 101 Townsend St., San Francisco, CA 94107, USA, betrieben. Beim Aufruf verarbeitet Cloudflare technisch notwendige Daten (IP-Adresse, Zeitpunkt, aufgerufene Adresse, Browser-Kennung), um die Seite auszuliefern und vor Angriffen zu schützen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (sicherer, stabiler Betrieb). Mit Cloudflare besteht ein Auftragsverarbeitungsvertrag; Cloudflare ist nach dem EU-US Data Privacy Framework zertifiziert, zusätzlich gelten Standardvertragsklauseln.</p><p>Zum Schutz vor Missbrauch zählen wir Anfragen je Stunde (z. B. Anmeldeversuche). Dazu speichern wir nur einen gesalzenen Hashwert der IP-Adresse, höchstens für die Dauer des Zeitfensters (bis zu einer Stunde).</p>`,
      acc: `<h2>4. Benutzerkonto</h2><p>Für ein Konto speichern wir E-Mail-Adresse, optional Ihren Namen, ein Passwort als PBKDF2-Hash, den Tarif, den Zeitpunkt und die Version Ihrer Zustimmung zu den AGB sowie die Bestätigung, dass Sie mindestens 16 Jahre alt sind. Nach der Anmeldung setzen wir ein Sitzungs-Cookie (mh_session, 30 Tage, HttpOnly), in der Datenbank liegt nur dessen Hashwert. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (Vertrag). Die Daten werden gelöscht, wenn Sie Ihr Konto löschen.</p>`,
      maps: `<h2>5. Ihre Karten und Gespräche</h2><p>Wir speichern, was Sie in eine Karte eingeben oder importieren: Namen und Lebensdaten von Personen, Orte, Jahreszahlen, Notizen, das Gespräch mit dem Assistenten und die Gestaltung. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO. Karten sind privat; erst wenn Sie im Menü „Teilen“ den Link freigeben, kann jeder mit dem Link die Karte sehen. Die Freigabe lässt sich jederzeit zurücknehmen.</p><p>Familiengeschichten enthalten oft Angaben über andere Menschen, manchmal auch über Herkunft, Religion oder Gesundheit (Art. 9 DSGVO). Bitte tragen Sie Angaben über lebende Personen nur ein, wenn Sie dazu berechtigt sind, und geben Sie solche Karten nur mit Bedacht frei. Die Verarbeitung für rein persönliche oder familiäre Zwecke fällt für Sie selbst unter Art. 2 Abs. 2 lit. c DSGVO.</p>`,
      ai: s.ai === 'anthropic'
        ? `<h2>6. KI-Assistent</h2><p>Wenn Sie im Chat schreiben, werden Ihre Nachricht, der bisherige Gesprächsverlauf und der aktuelle Inhalt der Karte an Anthropic PBC, 548 Market St, San Francisco, CA 94104, USA, übermittelt, um die Antwort zu erzeugen. Anthropic verarbeitet die Daten als Auftragsverarbeiter, verwendet API-Eingaben nicht zum Training und löscht sie nach kurzer Zeit. Die Übermittlung in die USA stützt sich auf Standardvertragsklauseln. Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO. Der Chat ist freiwillig; Sie können Karten auch ganz ohne KI von Hand oder per GEDCOM-Import anlegen.</p>`
        : s.ai === 'workers'
          ? `<h2>6. KI-Assistent</h2><p>Wenn Sie im Chat schreiben, werden Ihre Nachricht, der bisherige Gesprächsverlauf und der aktuelle Inhalt der Karte an Cloudflare Workers AI übermittelt (Cloudflare, Inc., siehe Abschnitt 3). Das Sprachmodell läuft in der Infrastruktur von Cloudflare; Eingaben werden nicht zum Training verwendet. Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO. Der Chat ist freiwillig; Sie können Karten auch von Hand oder per GEDCOM-Import anlegen.</p>` : '',
      geo: `<h2>7. Ortssuche und Stadtausschnitte</h2><p>Um einen Ort auf der Karte zu finden, sendet unser Server nur den Ortsnamen (z. B. „Witebsk, Belarus“) an den Dienst Nominatim der OpenStreetMap Foundation, St John’s Innovation Centre, Cowley Road, Cambridge, CB4 0WS, Vereinigtes Königreich. Namen von Personen und Ihre IP-Adresse werden nicht übermittelt. Für das Vereinigte Königreich besteht ein Angemessenheitsbeschluss der EU-Kommission. Ergebnisse speichern wir in einem Cache ohne Personenbezug.</p><p>Für die Stadtausschnitte auf der Karte (Straßen, Gebäude, Gewässer) lädt unser Server Kartenkacheln mit OpenStreetMap-Daten von OpenFreeMap (openfreemap.org, betrieben von Zsolt Ero, Ungarn/EU). Übermittelt wird nur, welcher Kartenausschnitt benötigt wird; Ihre IP-Adresse und Angaben über Personen werden nicht übermittelt. Die Kacheln werden bis zu 30 Tage im Cache von Cloudflare gespeichert.</p>`,
      google: s.google ? `<h2>8. Anmeldung mit Google</h2><p>Wenn Sie „Mit Google anmelden“ wählen, werden Sie zu Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland, weitergeleitet. Wir erhalten von Google Ihre E-Mail-Adresse, Ihren Namen und eine Kennung. Während der Anmeldung setzen wir ein kurzlebiges Cookie (mh_oauth, 10 Minuten) zum Schutz vor Fälschung. Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO; die Nutzung ist freiwillig.</p>` : '',
      mail: `<h2>9. E-Mails</h2><p>Wir senden E-Mails nur, wenn es nötig ist: Zurücksetzen des Passworts, Bestätigung einer Druckanfrage. ${s.mail ? 'Dafür nutzen wir den Versanddienst Resend (Resend, Inc., 2261 Market Street #5039, San Francisco, CA 94114, USA) als Auftragsverarbeiter; übermittelt werden Empfängeradresse und Inhalt der Nachricht. Die Übermittlung stützt sich auf das EU-US Data Privacy Framework bzw. Standardvertragsklauseln.' : ''} Newsletter versenden wir nicht.</p>`,
      prints: s.prints ? `<h2>10. Druckaufträge</h2><p>Für eine Druckanfrage verarbeiten wir die Druckdatei Ihrer Karte, Format und Ausstattung, Name, Lieferanschrift, E-Mail-Adresse, optional Telefonnummer und Ihre Nachricht. Die Druckdatei wird in Cloudflare R2 gespeichert. Wir geben Datei und Lieferanschrift an die Druckerei und das Versandunternehmen weiter, soweit es für die Ausführung nötig ist. Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO; für Rechnungen Art. 6 Abs. 1 lit. c DSGVO in Verbindung mit § 147 AO und § 257 HGB (gesetzliche Aufbewahrungsfristen von bis zu zehn Jahren). Die Druckdatei löschen wir spätestens 90 Tage nach Auslieferung.</p>` : '',
      cookies: `<h2>11. Cookies und lokaler Speicher</h2><p>Wir verwenden nur technisch notwendige Cookies (mh_session${s.google ? ', mh_oauth' : ''}). Im lokalen Speicher Ihres Browsers merken wir uns die gewählte Sprache und die zuletzt geöffnete Karte. Das ist für den von Ihnen gewünschten Dienst unbedingt erforderlich (§ 25 Abs. 2 Nr. 2 TDDDG); eine Einwilligung ist dafür nicht nötig.</p>`,
      rights: `<h2>12. Speicherdauer und Ihre Rechte</h2><p>Wir speichern Konto- und Karteninhalte, bis Sie sie löschen. Gelöschte Daten werden sofort aus der Datenbank entfernt; Sicherungskopien von Cloudflare laufen nach spätestens 30 Tagen ab.</p><p>Sie haben das Recht auf Auskunft (Art. 15), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung (Art. 18), Datenübertragbarkeit (Art. 20) und Widerspruch gegen Verarbeitungen auf Grundlage berechtigter Interessen (Art. 21 DSGVO). Eine Kopie aller Daten erhalten Sie jederzeit über „Meine Daten herunterladen“ im Kontomenü. Sie können sich außerdem bei einer Datenschutz-Aufsichtsbehörde beschweren, etwa bei der Behörde Ihres Wohnorts oder der für uns zuständigen Behörde (Art. 77 DSGVO).</p>`,
      age: `<h2>13. Mindestalter</h2><p>Ein Konto dürfen nur Personen ab 16 Jahren anlegen. Bei der Registrierung bestätigen Sie Ihr Alter.</p>`,
      chg: `<h2>14. Änderungen</h2><p>Wenn sich unser Dienst ändert, passen wir diese Erklärung an. Die jeweils aktuelle Fassung steht auf dieser Seite.</p>`,
    },
    en: {
      h: 'Privacy policy', tr: 'Translation for convenience. The German version is legally binding.',
      ctrl: `<h2>1. Controller</h2><p>${o.address()}<br>E-mail: ${o.email}</p><p>We have not appointed a data protection officer because we are not legally required to.</p>`,
      over: `<h2>2. In short</h2><ul><li>We use no analytics or advertising trackers and no third-party cookies. Fonts and map libraries are served from our own server.</li><li>Your maps are private until you share a link yourself.</li><li>We do not sell data and do not use your content to train AI models.</li><li>You can download your data at any time from the account menu and delete your account with all maps.</li></ul>`,
      host: `<h2>3. Hosting and server logs</h2><p>The website runs on Cloudflare Pages; the database (D1) and functions are also operated by Cloudflare, Inc., 101 Townsend St., San Francisco, CA 94107, USA. When you visit, Cloudflare processes technically necessary data (IP address, time, requested address, browser identifier) to deliver the site and protect it from attacks. Legal basis: Art. 6(1)(f) GDPR (secure, stable operation). We have a data processing agreement with Cloudflare; Cloudflare is certified under the EU-US Data Privacy Framework, and standard contractual clauses apply in addition.</p><p>To prevent abuse we count requests per hour (for example sign-in attempts). For this we store only a salted hash of the IP address, at most for the length of the time window (up to one hour).</p>`,
      acc: `<h2>4. Account</h2><p>For an account we store your e-mail address, optionally your name, your password as a PBKDF2 hash, your plan, the time and version of your acceptance of the terms and your confirmation that you are at least 16. After sign-in we set a session cookie (mh_session, 30 days, HttpOnly); the database holds only its hash. Legal basis: Art. 6(1)(b) GDPR (contract). The data is deleted when you delete your account.</p>`,
      maps: `<h2>5. Your maps and conversations</h2><p>We store what you enter into or import into a map: names and life dates of people, places, years, notes, the conversation with the assistant and the design. Legal basis: Art. 6(1)(b) GDPR. Maps are private; only when you turn on the link under “Share” can anyone with the link see the map. You can turn it off at any time.</p><p>Family histories often contain information about other people, sometimes about origin, religion or health (Art. 9 GDPR). Please enter information about living people only if you are entitled to, and share such maps with care. For you, processing for purely personal or household purposes falls under Art. 2(2)(c) GDPR.</p>`,
      ai: s.ai === 'anthropic'
        ? `<h2>6. AI assistant</h2><p>When you write in the chat, your message, the previous conversation and the current content of the map are sent to Anthropic PBC, 548 Market St, San Francisco, CA 94104, USA, to generate the reply. Anthropic acts as a processor, does not use API inputs for training and deletes them after a short time. The transfer to the USA is based on standard contractual clauses. Legal basis: Art. 6(1)(b) GDPR. The chat is optional; you can build maps by hand or by GEDCOM import without any AI.</p>`
        : s.ai === 'workers'
          ? `<h2>6. AI assistant</h2><p>When you write in the chat, your message, the previous conversation and the current content of the map are sent to Cloudflare Workers AI (Cloudflare, Inc., see section 3). The language model runs on Cloudflare’s infrastructure; inputs are not used for training. Legal basis: Art. 6(1)(b) GDPR. The chat is optional; you can build maps by hand or by GEDCOM import.</p>` : '',
      geo: `<h2>7. Place search and town insets</h2><p>To find a place on the map, our server sends only the place name (e.g. “Vitebsk, Belarus”) to the Nominatim service of the OpenStreetMap Foundation, St John’s Innovation Centre, Cowley Road, Cambridge, CB4 0WS, United Kingdom. Names of people and your IP address are not sent. The EU Commission has issued an adequacy decision for the United Kingdom. Results are kept in a cache that contains no personal data.</p><p>For the town insets on the map (streets, buildings, water) our server loads map tiles with OpenStreetMap data from OpenFreeMap (openfreemap.org, run by Zsolt Ero, Hungary/EU). Only the map area needed is sent; your IP address and information about people are not. Tiles are kept in Cloudflare’s cache for up to 30 days.</p>`,
      google: s.google ? `<h2>8. Sign-in with Google</h2><p>If you choose “Continue with Google”, you are redirected to Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland. Google sends us your e-mail address, your name and an identifier. During sign-in we set a short-lived cookie (mh_oauth, 10 minutes) to protect against forgery. Legal basis: Art. 6(1)(b) GDPR; using it is optional.</p>` : '',
      mail: `<h2>9. E-mails</h2><p>We send e-mails only when needed: password reset and confirmation of a print request. ${s.mail ? 'We use the delivery service Resend (Resend, Inc., 2261 Market Street #5039, San Francisco, CA 94114, USA) as a processor; the recipient address and the message content are transmitted. The transfer is based on the EU-US Data Privacy Framework or standard contractual clauses.' : ''} We do not send newsletters.</p>`,
      prints: s.prints ? `<h2>10. Print orders</h2><p>For a print request we process the print file of your map, format and finish, name, delivery address, e-mail address, optionally your phone number and your message. The print file is stored in Cloudflare R2. We pass the file and the delivery address to the print shop and the carrier as far as needed to fulfil the order. Legal basis: Art. 6(1)(b) GDPR; for invoices Art. 6(1)(c) GDPR with § 147 AO and § 257 HGB (statutory retention periods of up to ten years). We delete the print file no later than 90 days after delivery.</p>` : '',
      cookies: `<h2>11. Cookies and local storage</h2><p>We only use technically necessary cookies (mh_session${s.google ? ', mh_oauth' : ''}). In your browser’s local storage we remember the chosen language and the last map you opened. This is strictly necessary for the service you asked for (§ 25(2) no. 2 TDDDG), so no consent is required.</p>`,
      rights: `<h2>12. Retention and your rights</h2><p>We keep account and map content until you delete it. Deleted data is removed from the database immediately; Cloudflare backups expire after 30 days at the latest.</p><p>You have the right of access (Art. 15), rectification (Art. 16), erasure (Art. 17), restriction (Art. 18), data portability (Art. 20) and to object to processing based on legitimate interests (Art. 21 GDPR). You can get a copy of all your data at any time with “Download my data” in the account menu. You may also lodge a complaint with a supervisory authority, for example the one where you live or the one responsible for us (Art. 77 GDPR).</p>`,
      age: `<h2>13. Minimum age</h2><p>Only people aged 16 or over may create an account. You confirm your age when you sign up.</p>`,
      chg: `<h2>14. Changes</h2><p>When our service changes we update this policy. The current version is always on this page.</p>`,
    },
    ru: {
      h: 'Политика конфиденциальности', tr: 'Перевод для удобства. Юридическую силу имеет немецкая версия.',
      ctrl: `<h2>1. Ответственное лицо</h2><p>${o.address()}<br>E-mail: ${o.email}</p><p>Уполномоченный по защите данных не назначен, так как закон этого не требует.</p>`,
      over: `<h2>2. Коротко</h2><ul><li>Мы не используем аналитику, рекламные трекеры и сторонние cookie. Шрифты и картографические библиотеки загружаются с нашего сервера.</li><li>Ваши карты закрыты, пока вы сами не откроете доступ по ссылке.</li><li>Мы не продаём данные и не обучаем на ваших материалах модели ИИ.</li><li>В меню аккаунта можно в любой момент скачать свои данные и удалить аккаунт со всеми картами.</li></ul>`,
      host: `<h2>3. Хостинг и серверные журналы</h2><p>Сайт работает на Cloudflare Pages; база данных (D1) и функции также обслуживаются Cloudflare, Inc., 101 Townsend St., San Francisco, CA 94107, США. При посещении Cloudflare обрабатывает технически необходимые данные (IP-адрес, время, адрес страницы, идентификатор браузера), чтобы отдать страницу и защитить сайт от атак. Основание: ст. 6 абз. 1 п. f GDPR (безопасная и стабильная работа). С Cloudflare заключён договор об обработке данных; Cloudflare сертифицирована по EU-US Data Privacy Framework, дополнительно действуют стандартные договорные условия.</p><p>Для защиты от злоупотреблений мы считаем запросы за час (например, попытки входа). Для этого хранится только «солёный» хэш IP-адреса и не дольше самого временного окна (до одного часа).</p>`,
      acc: `<h2>4. Аккаунт</h2><p>Для аккаунта мы храним e-mail, по желанию имя, пароль в виде хэша PBKDF2, тариф, время и версию вашего согласия с условиями и подтверждение, что вам не меньше 16 лет. После входа устанавливается cookie сессии (mh_session, 30 дней, HttpOnly); в базе хранится только её хэш. Основание: ст. 6 абз. 1 п. b GDPR (договор). Данные удаляются вместе с аккаунтом.</p>`,
      maps: `<h2>5. Ваши карты и разговоры</h2><p>Мы храним то, что вы вносите или импортируете в карту: имена и даты жизни людей, места, годы, заметки, разговор с ассистентом и оформление. Основание: ст. 6 абз. 1 п. b GDPR. Карты закрыты; только когда вы включаете ссылку в меню «Поделиться», карту может увидеть любой, у кого есть ссылка. Доступ можно закрыть в любой момент.</p><p>Семейные истории часто содержат сведения о других людях, иногда о происхождении, религии или здоровье (ст. 9 GDPR). Вносите данные о живущих людях, только если имеете на это право, и открывайте такие карты обдуманно. Для вас самих обработка в чисто личных или семейных целях подпадает под ст. 2 абз. 2 п. c GDPR.</p>`,
      ai: s.ai === 'anthropic'
        ? `<h2>6. ИИ-ассистент</h2><p>Когда вы пишете в чат, ваше сообщение, предыдущая переписка и текущее содержимое карты передаются Anthropic PBC, 548 Market St, San Francisco, CA 94104, США, чтобы получить ответ. Anthropic действует как обработчик, не использует данные API для обучения и удаляет их через короткое время. Передача в США основана на стандартных договорных условиях. Основание: ст. 6 абз. 1 п. b GDPR. Чат необязателен: карту можно собрать вручную или импортом GEDCOM без ИИ.</p>`
        : s.ai === 'workers'
          ? `<h2>6. ИИ-ассистент</h2><p>Когда вы пишете в чат, ваше сообщение, предыдущая переписка и текущее содержимое карты передаются в Cloudflare Workers AI (Cloudflare, Inc., см. раздел 3). Языковая модель работает в инфраструктуре Cloudflare; данные не используются для обучения. Основание: ст. 6 абз. 1 п. b GDPR. Чат необязателен: карту можно собрать вручную или импортом GEDCOM.</p>` : '',
      geo: `<h2>7. Поиск мест и врезки городов</h2><p>Чтобы найти место на карте, наш сервер отправляет только название места (например, «Витебск, Беларусь») в сервис Nominatim фонда OpenStreetMap Foundation, St John’s Innovation Centre, Cowley Road, Cambridge, CB4 0WS, Великобритания. Имена людей и ваш IP-адрес не передаются. Для Великобритании действует решение Еврокомиссии о достаточном уровне защиты. Результаты хранятся в кэше без персональных данных.</p><p>Для врезок с городами (улицы, здания, вода) наш сервер загружает картографические плитки с данными OpenStreetMap у OpenFreeMap (openfreemap.org, его ведёт Zsolt Ero, Венгрия/ЕС). Передаётся только нужный участок карты; ваш IP-адрес и сведения о людях не передаются. Плитки до 30 дней хранятся в кэше Cloudflare.</p>`,
      google: s.google ? `<h2>8. Вход через Google</h2><p>Если вы выбираете «Войти через Google», вы переходите к Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ирландия. Google передаёт нам e-mail, имя и идентификатор. На время входа мы ставим короткоживущую cookie (mh_oauth, 10 минут) для защиты от подделки запроса. Основание: ст. 6 абз. 1 п. b GDPR; использование добровольно.</p>` : '',
      mail: `<h2>9. Письма</h2><p>Мы пишем только по делу: сброс пароля и подтверждение заявки на печать. ${s.mail ? 'Для отправки мы используем сервис Resend (Resend, Inc., 2261 Market Street #5039, San Francisco, CA 94114, США) как обработчика; передаются адрес получателя и текст письма. Передача основана на EU-US Data Privacy Framework или стандартных договорных условиях.' : ''} Рассылок мы не делаем.</p>`,
      prints: s.prints ? `<h2>10. Заказы печати</h2><p>Для заявки на печать мы обрабатываем файл вашей карты, формат и оформление, имя, адрес доставки, e-mail, по желанию телефон и ваше сообщение. Файл хранится в Cloudflare R2. Файл и адрес мы передаём типографии и службе доставки в объёме, необходимом для выполнения заказа. Основание: ст. 6 абз. 1 п. b GDPR; для счетов ст. 6 абз. 1 п. c GDPR в связи с § 147 AO и § 257 HGB (установленные законом сроки хранения до десяти лет). Файл для печати удаляется не позднее 90 дней после доставки.</p>` : '',
      cookies: `<h2>11. Cookie и локальное хранилище</h2><p>Мы используем только технически необходимые cookie (mh_session${s.google ? ', mh_oauth' : ''}). В локальном хранилище браузера запоминаются выбранный язык и последняя открытая карта. Это строго необходимо для работы сервиса, которым вы пользуетесь (§ 25 абз. 2 п. 2 TDDDG), поэтому согласие не требуется.</p>`,
      rights: `<h2>12. Сроки хранения и ваши права</h2><p>Данные аккаунта и карт хранятся, пока вы их не удалите. Удалённое сразу стирается из базы; резервные копии Cloudflare истекают не позднее чем через 30 дней.</p><p>Вы вправе получить информацию о своих данных (ст. 15), исправить (ст. 16), удалить (ст. 17), ограничить обработку (ст. 18), получить данные в переносимом виде (ст. 20) и возразить против обработки на основании законных интересов (ст. 21 GDPR). Копию всех данных можно в любой момент скачать через «Скачать мои данные» в меню аккаунта. Вы также можете подать жалобу в надзорный орган по защите данных, например по месту жительства (ст. 77 GDPR).</p>`,
      age: `<h2>13. Минимальный возраст</h2><p>Аккаунт могут создавать только люди от 16 лет. При регистрации вы подтверждаете свой возраст.</p>`,
      chg: `<h2>14. Изменения</h2><p>Если сервис меняется, мы обновляем эту политику. Действующая редакция всегда на этой странице.</p>`,
    },
  }[l];
  return `<h1>${T.h}</h1>${T.tr ? `<p class="tr">${T.tr}</p>` : ''}${T.ctrl}${T.over}${T.host}${T.acc}${T.maps}${T.ai}${T.geo}${T.google}${T.mail}${T.prints}${T.cookies}${T.rights}${T.age}${T.chg}`;
}

// ---------------- AGB ----------------
function terms(env, l) {
  const o = operator(env, l);
  const vat = { de: o.small ? 'Als Kleinunternehmer nach § 19 UStG weisen wir keine Umsatzsteuer aus.' : 'Alle Preise sind Endpreise einschließlich der gesetzlichen Umsatzsteuer.',
    en: o.small ? 'As a small business under § 19 UStG we do not charge VAT.' : 'All prices are final prices including statutory VAT.',
    ru: o.small ? 'Как малый предприниматель согласно § 19 UStG мы не начисляем НДС.' : 'Все цены окончательные и включают установленный законом НДС.' }[l];
  if (l === 'de') return `<h1>Allgemeine Geschäftsbedingungen</h1>
<h2>§ 1 Geltungsbereich, Anbieter</h2><p>Diese AGB gelten für die Nutzung von MapHeritage und für Druckaufträge. Anbieter ist ${o.name}, ${o.street}, ${o.zipCity} (siehe <a href="/impressum">Impressum</a>). Abweichende Bedingungen der Nutzer gelten nicht.</p>
<h2>§ 2 Leistungen</h2><p>MapHeritage ist ein Online-Dienst, mit dem Nutzer Familiengeschichten im Gespräch mit einem KI-Assistenten, von Hand oder per GEDCOM-Import als gestaltete Karte darstellen und als Bild herunterladen können. Der Tarif „Lite“ ist kostenlos und umfasst alle fünf Kartenstile und eine begrenzte Zahl von Bild-Downloads im Monat. Der Tarif „Pro“ umfasst zusätzlich die freie Gestaltung aller Elemente, große Exportformate und unbegrenzte Downloads; seine Bedingungen und sein Preis werden vor Abschluss gesondert mitgeteilt. Gedruckte Karten können gesondert bestellt werden (§ 7).</p>
<h2>§ 3 Konto</h2><p>Für die Nutzung ist ein Konto nötig. Nutzer müssen mindestens 16 Jahre alt sein und wahre Angaben machen. Zugangsdaten sind geheim zu halten. Mit der Registrierung kommt ein unentgeltlicher Nutzungsvertrag zustande, den beide Seiten jederzeit beenden können; Nutzer tun dies durch Löschen des Kontos.</p>
<h2>§ 4 Inhalte der Nutzer</h2><p>Die Rechte an eingegebenen Texten und Daten bleiben bei den Nutzern. Sie räumen uns die einfachen Rechte ein, die nötig sind, um die Inhalte zu speichern, darzustellen und – bei Freigabe eines Links – anderen zu zeigen. Nutzer sind dafür verantwortlich, dass sie Angaben über andere, insbesondere lebende Personen eintragen und freigeben dürfen. Rechtswidrige Inhalte sind untersagt; wir dürfen sie nach Kenntnis entfernen.</p>
<h2>§ 5 Heruntergeladene Bilder, KI-Hinweis</h2><p>Nutzer dürfen die erzeugten Kartenbilder für private Zwecke unbeschränkt verwenden, auch als Geschenk oder im Druck. Die Kartengrundlagen stammen aus gemeinfreien Quellen (Natural Earth, NOAA ETOPO1). Antworten und Ortsangaben des KI-Assistenten können fehlerhaft sein; bitte prüfen Sie Orte und Jahreszahlen.</p>
<h2>§ 6 Verfügbarkeit</h2><p>Wir bemühen uns um einen störungsfreien Betrieb, schulden aber beim kostenlosen Tarif keine bestimmte Verfügbarkeit. Wartung und Weiterentwicklung können den Dienst kurzzeitig einschränken.</p>
<h2>§ 7 Druckaufträge</h2><p>(1) Mit dem Absenden des Formulars „Druck bestellen“ geben Nutzer ein Angebot zum Kauf eines individuell nach ihren Vorgaben gefertigten Drucks ab. Der Vertrag kommt zustande, wenn wir die Bestellung per E-Mail mit Rechnung bestätigen. Die automatische Eingangsbestätigung ist noch keine Annahme.<br>(2) Es gelten die im Formular angezeigten Preise zuzüglich der dort genannten Versandkosten. ${vat} Die Zahlung erfolgt per Vorkasse auf Rechnung; die Fertigung beginnt nach Zahlungseingang. Die Lieferzeit beträgt in der Regel ${esc(env.PRINT_DAYS || '7–10')} Werktage ab Zahlungseingang.<br>(3) Farben können je nach Bildschirm und Papier leicht abweichen; das ist kein Mangel.<br>(4) Es gilt das gesetzliche Mängelhaftungsrecht. Transportschäden zeigen Sie bitte möglichst bald mit Fotos an; Ihre gesetzlichen Rechte bleiben davon unberührt.</p>
<h2>§ 8 Widerrufsrecht</h2><p>Verbrauchern steht grundsätzlich ein Widerrufsrecht nach der folgenden Belehrung zu.</p><p><b>Das Widerrufsrecht besteht nicht</b> bei Verträgen zur Lieferung von Waren, die nicht vorgefertigt sind und für deren Herstellung eine individuelle Auswahl oder Bestimmung durch den Verbraucher maßgeblich ist oder die eindeutig auf die persönlichen Bedürfnisse des Verbrauchers zugeschnitten sind (§ 312g Abs. 2 Nr. 1 BGB). Das gilt für Drucke Ihrer persönlichen Karte.</p>
<div class="box"><h3>Widerrufsbelehrung</h3><p><b>Widerrufsrecht.</b> Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen. Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag des Vertragsschlusses, bei Verträgen über Waren ab dem Tag, an dem Sie oder ein von Ihnen benannter Dritter, der nicht der Beförderer ist, die Waren in Besitz genommen haben. Um Ihr Widerrufsrecht auszuüben, müssen Sie uns (${o.name}, ${o.street}, ${o.zipCity}, E-Mail: ${o.email}${o.phone ? ', Telefon: ' + o.phone : ''}) mittels einer eindeutigen Erklärung (z. B. ein mit der Post versandter Brief oder eine E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Sie können dafür das beigefügte Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist. Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.</p>
<p><b>Folgen des Widerrufs.</b> Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt haben), unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet. Haben Sie verlangt, dass eine Dienstleistung während der Widerrufsfrist beginnen soll, so haben Sie uns einen angemessenen Betrag zu zahlen, der dem Anteil der bis zu Ihrem Widerruf bereits erbrachten Dienstleistungen im Vergleich zum Gesamtumfang der vorgesehenen Dienstleistungen entspricht.</p></div>
<div class="box"><h3>Muster-Widerrufsformular</h3><p>(Wenn Sie den Vertrag widerrufen wollen, dann füllen Sie bitte dieses Formular aus und senden Sie es zurück.)</p><p>An ${o.name}, ${o.street}, ${o.zipCity}, E-Mail: ${o.email}:</p><p>Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*) / die Erbringung der folgenden Dienstleistung (*)<br>– Bestellt am (*) / erhalten am (*)<br>– Name des/der Verbraucher(s)<br>– Anschrift des/der Verbraucher(s)<br>– Unterschrift des/der Verbraucher(s) (nur bei Mitteilung auf Papier)<br>– Datum</p><p>(*) Unzutreffendes streichen.</p></div>
<h2>§ 9 Haftung</h2><p>Wir haften unbeschränkt bei Vorsatz und grober Fahrlässigkeit, bei Verletzung von Leben, Körper oder Gesundheit und nach dem Produkthaftungsgesetz. Bei leichter Fahrlässigkeit haften wir nur für die Verletzung wesentlicher Vertragspflichten und begrenzt auf den vorhersehbaren, vertragstypischen Schaden. Für den Verlust von Daten haften wir nur, soweit er bei üblicher Datensicherung durch den Nutzer (z. B. „Meine Daten herunterladen“) nicht vermeidbar gewesen wäre.</p>
<h2>§ 10 Änderungen der AGB</h2><p>Wir können diese AGB mit Wirkung für die Zukunft ändern, wenn dafür ein triftiger Grund besteht (z. B. neue Funktionen oder Rechtslage). Registrierte Nutzer informieren wir mindestens vier Wochen vorher; widersprechen sie nicht bis zum Inkrafttreten, gelten die neuen AGB. Auf das Widerspruchsrecht und die Folge weisen wir in der Mitteilung hin.</p>
<h2>§ 11 Schlussbestimmungen</h2><p>Es gilt deutsches Recht unter Ausschluss des UN-Kaufrechts. Bei Verbrauchern gilt diese Rechtswahl nur, soweit nicht zwingende Verbraucherschutzvorschriften des Staates ihres gewöhnlichen Aufenthalts entgegenstehen. Zur Teilnahme an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle sind wir nicht bereit und nicht verpflichtet.</p>`;
  if (l === 'ru') return `<h1>Условия использования (AGB)</h1><p class="tr">Перевод для удобства. Юридическую силу имеет немецкая версия.</p>
<h2>§ 1 Сфера действия, исполнитель</h2><p>Эти условия действуют для использования MapHeritage и для заказов печати. Исполнитель: ${o.name}, ${o.street}, ${o.zipCity} (см. <a href="/impressum?lang=ru">Impressum</a>). Иные условия пользователей не применяются.</p>
<h2>§ 2 Услуги</h2><p>MapHeritage — онлайн-сервис, в котором семейную историю можно рассказать ИИ-ассистенту, внести вручную или импортировать из GEDCOM, получить оформленную карту и скачать её как изображение. Тариф «Lite» бесплатный: все пять стилей карты и ограниченное число скачиваний в месяц. Тариф «Pro» добавляет ручную настройку всех элементов, большие форматы экспорта и скачивания без лимита; условия и цена сообщаются отдельно до заключения договора. Печатные карты заказываются отдельно (§ 7).</p>
<h2>§ 3 Аккаунт</h2><p>Для работы нужен аккаунт. Пользователю должно быть не меньше 16 лет, данные должны быть правдивыми. Данные для входа нужно держать в тайне. Регистрация означает бесплатный договор пользования, который обе стороны могут прекратить в любой момент; пользователь делает это, удаляя аккаунт.</p>
<h2>§ 4 Материалы пользователей</h2><p>Права на тексты и данные остаются у пользователей. Они предоставляют нам простые права, нужные, чтобы хранить и показывать материалы, а при открытой ссылке — показывать их другим. Пользователь отвечает за то, что вправе вносить и открывать сведения о других людях, особенно живущих. Противоправные материалы запрещены; узнав о них, мы можем их удалить.</p>
<h2>§ 5 Скачанные изображения, об ИИ</h2><p>Созданные изображения карт можно без ограничений использовать в личных целях, в том числе как подарок и для печати. Картографическая основа взята из общественного достояния (Natural Earth, NOAA ETOPO1). Ответы и координаты ИИ-ассистента могут быть неточными; проверяйте места и годы.</p>
<h2>§ 6 Доступность</h2><p>Мы стараемся работать без сбоев, но на бесплатном тарифе не гарантируем определённую доступность. Обслуживание и развитие сервиса могут ненадолго ограничивать его работу.</p>
<h2>§ 7 Заказы печати</h2><p>(1) Отправляя форму «Заказать печать», пользователь делает предложение купить печать, изготовленную индивидуально по его указаниям. Договор заключается, когда мы подтверждаем заказ письмом со счётом. Автоматическое уведомление о получении заявки ещё не является принятием.<br>(2) Действуют цены, показанные в форме, плюс указанная там доставка. ${vat} Оплата — предоплата по счёту; изготовление начинается после поступления оплаты. Срок обычно ${esc(env.PRINT_DAYS || '7–10')} рабочих дней после оплаты.<br>(3) Цвета могут немного отличаться в зависимости от экрана и бумаги; это не недостаток.<br>(4) Действует установленная законом ответственность за недостатки. О повреждениях при доставке сообщите как можно скорее, с фотографиями; ваши законные права от этого не зависят.</p>
<h2>§ 8 Право на отказ (Widerruf)</h2><p>Потребители в принципе имеют право отказаться от договора согласно разъяснению ниже.</p><p><b>Права на отказ нет</b> для договоров на поставку товаров, которые не изготовлены заранее и для изготовления которых решающим является индивидуальный выбор потребителя или которые явно подогнаны под его личные потребности (§ 312g абз. 2 п. 1 BGB). Это относится к печати вашей личной карты.</p>
<div class="box"><h3>Разъяснение о праве на отказ</h3><p>Вы вправе в течение четырнадцати дней без указания причин отказаться от договора. Срок составляет четырнадцать дней со дня заключения договора, а для договоров о товарах — со дня, когда вы или названное вами третье лицо (не перевозчик) получили товар. Чтобы воспользоваться правом, сообщите нам (${o.name}, ${o.street}, ${o.zipCity}, e-mail: ${o.email}) однозначным заявлением (например, письмом или e-mail). Можно использовать образец формы ниже, но это необязательно. Для соблюдения срока достаточно отправить заявление до его истечения.</p><p><b>Последствия отказа.</b> Мы незамедлительно, не позднее чем через четырнадцать дней после получения заявления, вернём все полученные платежи, включая стоимость доставки (кроме дополнительных расходов, если вы выбрали не самую дешёвую стандартную доставку), тем же способом оплаты, без каких-либо сборов.</p></div>
<div class="box"><h3>Образец формы отказа</h3><p>Кому: ${o.name}, ${o.street}, ${o.zipCity}, e-mail: ${o.email}.<br>Настоящим я/мы (*) отказываюсь/отказываемся (*) от заключённого мной/нами (*) договора о покупке следующих товаров (*) / оказании следующей услуги (*)<br>– Заказано (*) / получено (*)<br>– Имя потребителя(ей)<br>– Адрес потребителя(ей)<br>– Подпись (только на бумаге)<br>– Дата</p><p>(*) Ненужное зачеркнуть.</p></div>
<h2>§ 9 Ответственность</h2><p>Мы несём неограниченную ответственность при умысле и грубой неосторожности, при причинении вреда жизни, телу или здоровью и по закону об ответственности за продукцию. При лёгкой неосторожности — только за нарушение существенных обязанностей и в пределах предвидимого типичного ущерба. За потерю данных отвечаем, только если её нельзя было избежать обычным резервным копированием (например, «Скачать мои данные»).</p>
<h2>§ 10 Изменение условий</h2><p>Мы можем изменить условия на будущее при веском основании (новые функции, изменение законов). Зарегистрированных пользователей предупреждаем не меньше чем за четыре недели; если они не возразят до вступления в силу, действуют новые условия. О праве возразить и последствиях сообщим в уведомлении.</p>
<h2>§ 11 Заключительные положения</h2><p>Применяется право Германии, без Конвенции ООН о купле-продаже. Для потребителей выбор права действует, лишь пока не противоречит обязательным нормам защиты потребителей страны их проживания. Мы не готовы и не обязаны участвовать в процедурах в арбитражном органе по делам потребителей.</p>`;
  return `<h1>Terms of service (AGB)</h1><p class="tr">Translation for convenience. The German version is legally binding.</p>
<h2>§ 1 Scope, provider</h2><p>These terms apply to the use of MapHeritage and to print orders. The provider is ${o.name}, ${o.street}, ${o.zipCity} (see <a href="/impressum?lang=en">legal notice</a>). Conflicting terms of users do not apply.</p>
<h2>§ 2 Services</h2><p>MapHeritage is an online service that turns family histories — told to an AI assistant, entered by hand or imported from GEDCOM — into a designed map that can be downloaded as an image. The “Lite” plan is free and includes all five map styles and a limited number of downloads per month. The “Pro” plan adds manual design of every element, large export sizes and unlimited downloads; its conditions and price are communicated separately before a contract is made. Printed maps can be ordered separately (§ 7).</p>
<h2>§ 3 Account</h2><p>An account is required. Users must be at least 16 years old and give truthful information. Sign-in details must be kept secret. Registration creates a free contract of use that either side may end at any time; users do this by deleting the account.</p>
<h2>§ 4 User content</h2><p>Rights to the texts and data entered stay with the users. They grant us the simple rights needed to store and display the content and, if a link is shared, to show it to others. Users are responsible for being entitled to enter and share information about other people, especially living people. Unlawful content is prohibited; we may remove it once we become aware of it.</p>
<h2>§ 5 Downloaded images, AI notice</h2><p>Users may use the generated map images for private purposes without restriction, including as gifts and in print. The cartographic base comes from public-domain sources (Natural Earth, NOAA ETOPO1). Replies and locations from the AI assistant may be wrong; please check places and years.</p>
<h2>§ 6 Availability</h2><p>We aim for uninterrupted operation but owe no particular availability on the free plan. Maintenance and development may briefly limit the service.</p>
<h2>§ 7 Print orders</h2><p>(1) By sending the “Order a print” form, users make an offer to buy a print made individually to their specification. The contract is concluded when we confirm the order by e-mail with an invoice. The automatic receipt e-mail is not yet an acceptance.<br>(2) The prices shown in the form apply, plus the shipping costs shown there. ${vat} Payment is in advance by invoice; production starts after payment is received. Delivery normally takes ${esc(env.PRINT_DAYS || '7–10')} working days after payment.<br>(3) Colours may differ slightly depending on screen and paper; this is not a defect.<br>(4) Statutory warranty law applies. Please report transport damage as soon as possible with photos; your statutory rights remain unaffected.</p>
<h2>§ 8 Right of withdrawal</h2><p>Consumers generally have a right of withdrawal as set out below.</p><p><b>There is no right of withdrawal</b> for contracts for the supply of goods that are not prefabricated and for whose production an individual selection or determination by the consumer is decisive, or that are clearly tailored to the consumer’s personal needs (§ 312g (2) no. 1 BGB). This applies to prints of your personal map.</p>
<div class="box"><h3>Withdrawal instructions</h3><p>You have the right to withdraw from this contract within fourteen days without giving any reason. The withdrawal period is fourteen days from the day the contract is concluded, and for goods from the day on which you, or a third party other than the carrier named by you, take possession of the goods. To exercise the right of withdrawal, you must inform us (${o.name}, ${o.street}, ${o.zipCity}, e-mail: ${o.email}) of your decision by a clear statement (e.g. a letter sent by post or an e-mail). You may use the model withdrawal form below, but it is not obligatory. To meet the deadline it is sufficient to send your communication before the period has expired.</p><p><b>Effects of withdrawal.</b> If you withdraw, we will reimburse all payments received from you, including delivery costs (except supplementary costs from choosing a delivery other than the least expensive standard delivery offered by us), without undue delay and in any event within fourteen days of the day we are informed of your decision, using the same means of payment, without any fees.</p></div>
<div class="box"><h3>Model withdrawal form</h3><p>To ${o.name}, ${o.street}, ${o.zipCity}, e-mail: ${o.email}:<br>I/We (*) hereby give notice that I/We (*) withdraw from my/our (*) contract of sale of the following goods (*) / for the provision of the following service (*)<br>– Ordered on (*) / received on (*)<br>– Name of consumer(s)<br>– Address of consumer(s)<br>– Signature of consumer(s) (only if on paper)<br>– Date</p><p>(*) Delete as appropriate.</p></div>
<h2>§ 9 Liability</h2><p>We are liable without limitation for intent and gross negligence, for injury to life, body or health and under the Product Liability Act. For slight negligence we are liable only for breach of essential contractual obligations, limited to the foreseeable damage typical for the contract. We are liable for loss of data only insofar as it could not have been avoided by the user’s usual backups (e.g. “Download my data”).</p>
<h2>§ 10 Changes to the terms</h2><p>We may change these terms for the future if there is a valid reason (e.g. new features or legal changes). We inform registered users at least four weeks in advance; if they do not object before the changes take effect, the new terms apply. We point out the right to object and its consequence in the notice.</p>
<h2>§ 11 Final provisions</h2><p>German law applies, excluding the UN Convention on Contracts for the International Sale of Goods. For consumers, this choice of law applies only insofar as mandatory consumer protection provisions of their country of habitual residence are not affected. We are neither willing nor obliged to take part in dispute resolution before a consumer arbitration board.</p>`;
}

const PAGES = { impressum, datenschutz: privacy, agb: terms };
const NAV = { de: ['Impressum', 'Datenschutz', 'AGB', 'Zur Startseite'], en: ['Legal notice', 'Privacy', 'Terms', 'Home'], ru: ['Impressum', 'Конфиденциальность', 'Условия', 'На главную'] };
const TITLES = { impressum: { de: 'Impressum', en: 'Legal notice', ru: 'Impressum' }, datenschutz: { de: 'Datenschutzerklärung', en: 'Privacy policy', ru: 'Политика конфиденциальности' }, agb: { de: 'AGB', en: 'Terms of service', ru: 'Условия использования' } };

export function legalPage(page, request, env) {
  const l = pickLang(request), body = PAGES[page](env, l), n = NAV[l];
  const langs = LANGS.map((x) => x === l ? `<b>${x.toUpperCase()}</b>` : `<a href="/${page}?lang=${x}" hreflang="${x}">${x.toUpperCase()}</a>`).join(' · ');
  const html = `<!doctype html><html lang="${l}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/fonts/fonts.css"><link rel="stylesheet" href="/assets/style.css">
<title>${TITLES[page][l]} — MapHeritage</title><meta name="robots" content="noindex">
<style>.lg{max-width:760px;margin:0 auto;padding:clamp(24px,5vw,64px) clamp(16px,4vw,32px) 64px;font:17px/1.6 var(--serif)}.lg h1{font-size:clamp(32px,5vw,46px);margin:0 0 18px}.lg h2{font-size:21px;margin:30px 0 8px}.lg h3{font-size:18px;margin:0 0 8px}.lg p,.lg li{margin:0 0 10px}.lg .tr{font-style:italic;color:var(--ink-2)}.lg .box{border:1px solid var(--rule);background:var(--card);padding:14px 18px;margin:16px 0}.lg mark.miss{background:#f6d5cc;color:#7A2215;font:600 14px var(--ui);padding:1px 4px}.lg .upd{color:var(--ink-2);font-size:14px;margin-top:40px}.ltop{display:flex;gap:14px;align-items:center;padding:14px clamp(16px,4vw,48px);border-bottom:1.5px solid var(--ink);flex-wrap:wrap}.ltop .langs{margin-left:auto;font:14px var(--ui)}.lnav{font:15px var(--ui);display:flex;gap:16px;flex-wrap:wrap;margin-bottom:26px}</style></head>
<body><header class="ltop"><a class="brand" href="/"><svg class="logo" width="30" height="30" viewBox="0 0 64 64" fill="none" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 50 L19 14 L32 38 L45 14 L52 50" stroke="currentColor" stroke-width="6"/><circle cx="12" cy="50" r="6.5" fill="#9B2F1F"/></svg><span>MapHeritage</span></a><span class="langs">${langs}</span></header>
<main class="lg"><nav class="lnav"><a href="/impressum?lang=${l}">${n[0]}</a><a href="/datenschutz?lang=${l}">${n[1]}</a><a href="/agb?lang=${l}">${n[2]}</a><a href="/">${n[3]}</a></nav>${body}<p class="upd">${UPDATED[l]}${page === 'agb' ? ' · ' + TERMS_VERSION : ''}</p></main></body></html>`;
  return new Response(html, { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'public, max-age=300', 'content-language': l } });
}
